name:                hasktorch-codegen
version:             0.1.0.0
synopsis:            Torch for tensors and neural networks in Haskell
description:         Code generation tools
license:             BSD3
author:              Austin Huang
github: austinvhuang/hasktorch

dependencies:
- base >=4.7 && <5
- containers >= 0.5.7
- megaparsec >= 5.3
- pretty-show >= 1.6.13
- text >= 1.2.2.2

library:
  source-dirs:
  - src
  - src/aten

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - QuickCheck
      - hspec
      - hasktorch-codegen

executables:
  codegen-generic:
    source-dirs:      exe/generic
    main:             RenderGeneric.hs
    dependencies:
      - hasktorch-codegen

  codegen-concrete:
    source-dirs:      exe/concrete
    main:             RenderConcrete.hs
    dependencies:
      - hasktorch-codegen

  codegen-managed:
    source-dirs:      exe/managed
    main:             RenderManaged.hs
    dependencies:
      - hasktorch-codegen
      - raw-strings-qq >= 1.1

  aten-process-spec:
    source-dirs:      exe/aten
    main:             ProcessSpec.hs
    dependencies:
      - base >=4.7 && <5
      - aeson >= 1.1
      - aeson-pretty >= 0.8.5
      - bytestring >= 0.10.8
      - singletons >=2.2
      - text >=1.2.2.2
      - yaml >=0.8.25

